apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            configMapKeyRef:
             name: wordpress-configmap
             key: mysql_password
         - name: MYSQL_DATABASE
           valueFrom:
            configMapKeyRef:
             name: wordpress-configmap
             key: mysql_name
         - name: MYSQL_USER
           valueFrom:
            configMapKeyRef:
             name: wordpress-configmap
             key: mysql_username
         - name: MYSQL_PASSWORD
           valueFrom:
            configMapKeyRef:
             name: wordpress-configmap
             key: mysql_userpassword
      nodeSelector:
          backend: mysql
