apiVersion: v1
kind: Service
metadata:
  labels: 
    app: wordpress
  name: wordpress 
spec:
  type: NodePort
  selector:
     app: wordpress
  ports:
     - targetPort: 80
       port: 80
       protocol: TCP
       